### ISSUE TITLE
Wrong update of version for breaking change

### ISSUE THREAD

**Issue by ghilainm** [diffplug/spotless-changelog#35]
Despite a breaking change is correctly detected, the second digit of the x.y.z pattern is updated in the next version.

Maybe it is the expected behaviour, but I don't understand it.

Indeed, as far as I see in the code it is the expected behavior:

```
if (last.getMajor() == 0) {
				boolean bumpMinor = ifFoundBumpBreaking.stream().anyMatch(unreleasedChanges::contains) ||
						ifFoundBumpAdded.stream().anyMatch(unreleasedChanges::contains);
				if (bumpMinor) {
					return "0." + (last.getMinor() + 1) + ".0";
				} else {
					return "0." + last.getMinor() + "." + (last.getMicro() + 1);
				}
			}
```

**Comment by nedtwigg** [comment]
A breaking change turns `n.0.0` into `(n+1).0.0` (e.g. `1.0.0` -> `2.0.0`), except where `n=0` (e.g. `0.1.0` -> `0.2.0`). The reason is that `0.x` signifies "we are not doing Semver", and once you transition to `1.x` that's the start of "we are making semver guarantees".

I wrote a bit about this [here](https://github.com/diffplug/spotless-changelog#pre-10-0x-and-other-forms-of-perfomative-insecurity).

**Comment by ghilainm** [comment]
Sorry mate, thx for the pointer to the documentation. I didn't read that part, my mistake, it is crystal clear :).

Thx a lot for taking the time to answer :). At least if somebody does the same mistake as me he may find this issue :).
