### ISSUE TITLE
README says enforceCheck default is true, but it is false

### ISSUE THREAD

**Issue by josephearl** [diffplug/spotless-changelog#38]
I have a `CHANGELOG.md` with an issue like a missing `## [Unreleased]` header

Expected:

`./gradlew check` fails out of the box with just the plugin added (based on the README).

Actual:

`./gradlew check` does not fail.

Only once the following configuration is added does it fail:

```
spotlessChangelog {
  enforceCheck true
}
```

Gradle 7.3.3

**Comment by nedtwigg** [comment]
Wow, that's a silly bug. Thanks for reporting, you are correct!

Changing the default at this point would represent a breaking change. We also need to bump our required JRE runtime from 8 to 11 so that we can get the latest available JGit.

I think the next release will be a `3.0`, and the breaking changes will be this change to the default value, and also a bump from java 8 to 11.

**Comment by nedtwigg** [comment]
Fixed in `3.0.1`.
