### ISSUE TITLE
versionNext property evaluation

### ISSUE THREAD

**Issue by sdavids** [diffplug/spotless-changelog#6]
Works:

```
plugins {
  id 'java-library'
  id 'com.diffplug.spotless-changelog' version '1.1.0'
}

sourceCompatibility = JavaVersion.VERSION_1_8

repositories.mavenCentral()

spotlessChangelog {
  changelogFile 'CHANGELOG.adoc'
}

version = project.spotlessChangelog.versionNext
```

Does not work:

```
plugins {
  id 'java-library'
  id 'com.diffplug.spotless-changelog' version '1.1.0'
}

sourceCompatibility = JavaVersion.VERSION_1_8

repositories.mavenCentral()

version = project.spotlessChangelog.versionNext

spotlessChangelog {
  changelogFile 'CHANGELOG.adoc'
}
```

Error message:

```
> Looked for changelog at '/<redacted>/CHANGELOG.md', but it was not present.
```

**Comment by sdavids** [comment]
Same with `version = project.spotlessChangelog.versionLast`.

**Comment by nedtwigg** [comment]
You are correct, and this is working as intended.  The error message is bad, and should instead say something closer to "You have to configure the `spotlessChangelog` block before calling `spotlessChangelog.versionBlah`."

It's easy to make sure that people don't modify the configuration after they call `versionLast/Next`

https://github.com/diffplug/spotless-changelog/blob/7ff2c93597fb60cb576f29f10d7684449687a971/spotless-changelog-plugin-gradle/src/main/java/com/diffplug/spotless/changelog/gradle/ChangelogExtension.java#L74-L77

This case is a little harder, because we have to distinguish between "I want to use all defaults, and the file really is missing" versus "I'm setting up the changelog too low in my script".
