### ISSUE TITLE
`v` tag prefix  cause error for command: changelogPrint

### ISSUE THREAD

**Issue by xmlking** [diffplug/spotless-changelog#9]
I am using `v` prefix for tagging. I configured `tagPrefix("v")` for spotless as well as   ` prefix = "v"` for `scmVersion`
https://github.com/xmlking/micro-apps/blob/develop/build.gradle.kts

Why I am getting error if my changelog has `[v1.6.3 ]` ? 
my change log is produced by [git-chglog](https://github.com/git-chglog/git-chglog)

```kt
scmVersion {
    useHighestVersion = true

    tag(closureOf<TagNameSerializationConfig> {
        prefix = "v" // golang and appctl need SemVer tags with `v` prefix
        versionSeparator = ""
    })

    branchVersionIncrementer = mapOf(
        "feature/.*" to "incrementMinor",
        "hotfix/.*" to "incrementPatch",
        "release/.*" to "incrementPrerelease",
        "develop" to "incrementPatch",
        "master" to "incrementMinor"
    )
}

version = scmVersion.version
val shortRevision = scmVersion.scmPosition.shortRevision
val isSnapshot = version.toString().endsWith("-SNAPSHOT")
val isCI = System.getenv("CI").isNullOrBlank().not()
if (!project.hasProperty("release.quiet")) {
    println("Version: $version,  Branch: ${scmVersion.scmPosition.branch}, isCI: $isCI")
}

spotlessChangelog {
    changelogFile("CHANGELOG.md")
    // enforceCheck true
    setAppendDashSnapshotUnless_dashPrelease(true)
    ifFoundBumpBreaking("**BREAKING**")
    ifFoundBumpAdded("### Added", "### Feat")
    tagPrefix("v")
    commitMessage("Release v{{version}}")
    remote("origin")
    branch("release")
}

println("SpotlessChangelog versionNext: ${spotlessChangelog.versionNext} versionLast: ${spotlessChangelog.versionLast}")

```

## Error

`gradle changelogPrint`

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/s.../build.gradle.kts' line: 116

* What went wrong:
invalid version "v0.1.1": non-numeric "v0"
> For input string: "v0"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

```

**Comment by nedtwigg** [comment]
There are two steps:

- parse the versions from the changelog file
- append `tagPrefix` to them when creating a git tag for a new release

It expects the changelog to just be `[1.2.3]`, not `[v1.2.3]`.  Tag prefix is most useful if you have multiple subprojects which each have their own changelog, then you can tag one with `lib/`, and another with `plugin-blah/`, etc.

If you really want the versions in your changelog to be `v1.2.3`, you can do that, but you'll need to make [a custom `NextVersionFunction`](https://github.com/diffplug/spotless-changelog/blob/master/ALTERNATE_VERSION_SCHEMAS.md), which is easy to do since yours is just a small modification to the standard `Semver`.  However, you'll then want `tagPrefix("")`, otherwise you'll get tags like `vv1.2.3`.

**Comment by xmlking** [comment]
@nedtwigg thanks for the suggestion. 
I did recommend changes, it worked. 
https://github.com/xmlking/micro-apps/commit/a8a5f3f761cafb3aaf34a451f28af93e46b14ddd

how do I fix `versionLast` ,  is there a way to provide `custom VersionLastFunction`?

Wonder if you are interested to make providing custom `VersionLastFunction`  easy for Kotlin Gradle DSL users.

E.g., 
```
versionSchema(SemverRemoveV::class.java)
# to
versionSchema { 
    VersionLastFunction = (unreleasedChanges: String, lastVersion: String) -> {
        ...
    }
}

```


```
gradle changelogPrint                                                                     

> Configure project :
Version: 1.6.5-SNAPSHOT,  Branch: develop, isCI: false
SpotlessChangelog version Next: 1.6.5-SNAPSHOT  Last: v1.6.4

> Task :changelogPrint
micro-apps v1.6.4 -> 1.6.5-SNAPSHOT
```

**Comment by nedtwigg** [comment]
> how do I fix versionLast

By removing the `v` from your changelog.

SpotlessChangelog has two versions that it cares about

- `versionLast` - the most recent published release, is **parsed** from the changelog, not computed by a function
- `versionNext` - the calculated value of the next release, were it to be published today.  This is calculated from `versionLast` and the unreleased changes.

So if your changelog is this:

```
## [Unreleased]
### Added
- A great feature

## [1.0.0] - 2019-12-02
Initial release.
```

Your `NextVersionFunction`, which is just `f(unreleasedChanges, lastVersion)`, is going to get passed `f('### Added\n- A great feature', '1.0.0')`.

If your changelog had this content:

```
## [Unreleased]
🐻🐻🐻
🐻🐻

## [🚫🚽📃] - 2019-12-02
Initial release.
```

then `NextVersionFunction` would get called with `f('🐻🐻🐻\n🐻🐻', '🚫🚽📃')`.  The only function involved anywhere is `NextVersionFunction`, which is just `BiFunction<String, String, String>`, and a parser to parse `lastVersion` and `unreleasedChanges`.  That's the simplest way to do it, and you can do anything you want with it.

If you want your changelog to have `[v1.2.3]` instead of `[1.2.3]`, you can do that.  You'll just have to remove the leading `v`, delegate to Semver, then add the `v` back on, all within your custom `NextVersionFunction`.

**Comment by xmlking** [comment]
I am also not a big fan of adding `v` prefix for git tags.  But I am forced to add it for 
1. GoLang - go modules won't work without `v` tag [prefix](https://github.com/golang/go/wiki/Modules)
2.  Google [appctl](https://github.com/xmlking/micro-apps/tree/develop/config#setup) also need git tags with `V` prefix. 

The tool I used for generating CHANGELOG.md  [git-chglog](https://github.com/git-chglog/git-chglog) will use git tags to produce CHANGELOG, even  if I temporarily remove `v` from generated CHANGELOG, it gets added again when  run `git-chglog  -o CHANGELOG.md -next-tag 2.0.0`


it looks awkward to add a class to `build.gradle.kts`, will you consider to make better Gradle DSL by allowing passing s `closure`  function?

```kt
class SemverRemoveV : Semver() {
    override fun nextVersion(unreleasedChanges: String, lastVersion: String): String {
        return if (lastVersion.startsWith("v"))
            super.nextVersion(unreleasedChanges, lastVersion.removePrefix("v"))
        else
            super.nextVersion(unreleasedChanges, lastVersion)
    }
}


spotlessChangelog {
    changelogFile("CHANGELOG.md")
    // enforceCheck true
    setAppendDashSnapshotUnless_dashPrelease(true)
    ifFoundBumpBreaking("**BREAKING**")
    ifFoundBumpAdded("### Added", "### Feat")
    tagPrefix("v")
    versionSchema(SemverRemoveV::class.java)
    commitMessage("Release v{{version}}")
    remote("origin")
    branch("release")
}
```

**Comment by nedtwigg** [comment]
Sounds like a common need!  Thanks for following up, I'll open enhancements against these.

**Comment by nedtwigg** [comment]
Btw, I think what you want is this:

```gradle
class SemverWithVPrefix : Semver() {
    override fun nextVersion(unreleasedChanges: String, lastVersion: String): String {
        "v" + super.nextVersion(unreleasedChanges, lastVersion.removePrefix("v"))
    }
}

spotlessChangelog {
    ...
    versionSchema(SemverWithVPrefix::class.java)
    tagPrefix("")
}

The problem with closures is up-to-date checking.  The `NextVersionFunction` needs to change if its code changes.

**Comment by nedtwigg** [comment]
After looking at it a bit, I've decided not to open enhancements.  I think they would require as much documentation as this whole issue, so better to just leave the issue as the documentation.  I dug a bit through the docs `git-chglog`, and I didn't see anywhere that the changelog versions were named `v1.2.3`, e.g. https://github.com/git-chglog/git-chglog/blob/master/CHANGELOG.md.  I understand that the **tags** are `v`, but that doesn't mean the changelog entries are.  And with the workaround above, it's fine if they are.

**Comment by xmlking** [comment]
I think the above two options are good for most cases.  I will stick with Option 2.
`git-chglog` CLI uses tag names `as-is` when it generateing  `CHANGELOG.md` 

as you can see I changed to `v` style tags after release:  1.5.0 
https://github.com/xmlking/micro-apps/blob/develop/CHANGELOG.md
Tag History: https://github.com/xmlking/micro-apps/releases

I will find a way customize git-chglog config via [.chglog/CHANGELOG.tpl.md](https://raw.githubusercontent.com/xmlking/micro-apps/develop/.chglog/CHANGELOG.tpl.md)

if you come across any good CHANGELOG generators for Gradle, please let me know

I enjoy your plugins. they are **SPOTLESS** 
Thanks

**Comment by xmlking** [comment]
I fixed my git-chglog `CHANGELOG.tpl.md` so need to apply custom `versionSchema` 

https://github.com/xmlking/micro-apps/commit/91521db5882f15b240c98d482e2d93ff55c95104

**Comment by nedtwigg** [comment]
Looks like you've got 11 tags pre-v.  You could just make new `v` tags on top of them.

FWIW, spotless-changelog only cares about the latest release.  You can have gobbledygook before it, and spotless-changelog doesn't care.  So if the most recent release has `v`, that's all spotless-changelog will ever see.
